---
superset_farm_certs_dir: /var/certs
superset_farm_image: ghcr.io/isisneutronmuon/analytics-data-platform-superset:d1b4efd83ee5ea490bb7429bdd64f519d7e7f343
superset_farm_work_dir_prefix: /var/superset_farm
