---
keycloak_db_dbname: keycloak
keycloak_db_host: "{{ groups['postgres'][0] }}"
keycloak_db_port: 5432
keycloak_db_user: "{{ vault_postgres_db_user }}"
keycloak_db_passwd: "{{ vault_postgres_db_passwd }}"
keycloak_bootstrap_admin_user: "{{ vault_keycloak_bootstrap_admin_user }}"
keycloak_bootstrap_admin_passwd: "{{ vault_keycloak_bootstrap_admin_passwd }}"
