---
keycloak_db_dbname: keycloak
keycloak_db_host: "{{ groups['postgres'][0] }}"
keycloak_db_port: 5432
keycloak_db_user: "{{ vault_postgres_db_user }}"
keycloak_db_passwd: "{{ vault_postgres_db_passwd }}"
keycloak_bootstrap_admin_passwd: "{{ vault_keycloak_bootstrap_admin_passwd }}"
keycloak_java_keystore_passwd: "{{ vault_keycloak_java_keystore_passwd }}"

reverse_proxy_external_ip: 130.246.214.124
