$ANSIBLE_VAULT;1.1;AES256
34616366393963316164323233383731616138356433663262646431613765653663653664343835
3037373139313839663665323961616463663831613135620a616166326161303165383963356563
39306362613261656237323361616435626464376530333166353437366132643264666630663233
3566313632343336300a623563373461396466613163366361393933663131363631316665366631
39376362323865323865356230366362393531663230343630663763323137613738666135313532
37323338353432363365393034306364303633323531616338366432363061633863663337616232
38393334396631343133333239633830643564623535373333626137313735636131353136626233
30346631363361333565633465336236386561633037356361386438386338656633306364656433
31333132613832353962333861323232333335353333366166643663336564366638316634303264
63643361643238303139323336393337303561623338333961653136323037356162613863653165
61346631383966636333346462363634623961396235353863633135303862393065346536663662
66613066303030376263396339613039326164616664306333336232613732306137656331313238
34376163623663303566656136623361623464373962326365333934303266306530393234313863
32393261393438353532656337386231326236303436616466383331393762633132396462316335
64636165353062643263393736623162663964313033373037623233623932323431306563373465
31626362336265363732
