---
- name: Configure traefik
  hosts: traefik
  roles:
    - role: base_configure
    - role: geerlingguy.pip
      become: true
    - role: docker_configure
    - role: docs
      become: true
    - role: traefik
