---
- name: Configure trino
  hosts: trino
  roles:
    - role: system_configure
    - role: cephfs_mount
    - role: geerlingguy.pip
      become: true
    - role: docker_configure
    - role: trino
