---
- name: Fetch and update available packages
  become: true
  ansible.builtin.apt:
    cache_valid_time: "{{ apt_cache_valid_time }}"
    update_cache: true
    upgrade: true
  retries: 3
  delay: 5
- name: Ensure timezone package available
  become: true
  ansible.builtin.apt:
    pkg:
      - tzdata
  retries: 3
  delay: 5
- name: Set timezone
  become: true
  community.general.timezone:
    name: "Europe/London"
