---
- name: Read global configuration
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        dir: "configs/shared"
    - ansible.builtin.include_vars:
        file: "{{ item }}"
      loop: "{{ config_files }}"

- name: Provision private network
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create private network
      openstack.cloud.network:
        cloud: "{{ openstack_cloud_name }}"
        name: "{{ openstack_virtual_network.name }}"
        external: false
        admin_state_up: true
        state: present
    - name: Create private network subnets
      openstack.cloud.subnet:
        cloud: "{{ openstack_cloud_name }}"
        network_name: "{{ openstack_virtual_network.name }}"
        name: "{{ subnet.name }}"
        cidr: "{{ subnet.cidr }}"
        gateway_ip: "{{ subnet.gateway_ip }}"
        state: present
      loop: "{{ openstack_virtual_network.subnets }}"
      loop_control:
        loop_var: subnet
    - name: Attach to External router
      openstack.cloud.router:
        cloud: "{{ openstack_cloud_name }}"
        state: present
        name: "{{ openstack_router.name }}"
        interfaces: "{{ openstack_virtual_network.subnets | map(attribute='name') }}"
        external_gateway_info: "{{ openstack_router.external_gateway_info }}"
