---
postgres_db_user: "{{ vault_postgres_db_user }}"
postgres_db_passwd: "{{ vault_postgres_db_passwd }}"
postgres_db_names:
  - keycloak
  - openfga
  - lakekeeper
  - superset_farm

minio_root_user: "{{ vault_minio_root_user }}"
minio_root_password: "{{ vault_minio_root_passwd }}"
