---
# VM
openstack_server_name: superset_farm
openstack_security_group_name: superset
openstack_security_group_description: Ingress to superset ports
openstack_security_group_rules:
  - direction: ingress
    ether_type: IPv4
    protocol: tcp
    port_range_min: 8088 # how can we not duplicate this...
    port_range_max: 8089
openstack_flavor: l3.xsmall
openstack_security_groups: [default, "{{ openstack_security_group_name }}"]

# Image
superset_container_image: ghcr.io/martyngigg/adp-superset-forked:901412e

# DB
superset_metadb_host: "{{ vault_db_host }}"
superset_metadb_port: "{{ vault_db_port }}"
superset_metadb_name: "{{ vault_superset_metadb_name }}"
superset_metadb_user: "{{ vault_superset_metadb_user }}"
superset_metadb_passwd: "{{ vault_superset_metadb_passwd }}"
