$ANSIBLE_VAULT;1.1;AES256
64313866633637643538353331646661373831336439376632656361643663386565643365623939
3331653034303665656532363237333239613338306332380a623834643230663238646462316361
34303730346531353335343435323437393066666636656637346466306335356430333838393335
3666303234366137300a626132616133643938393632363766393734373638373433346665626565
66376635633162326565303031336663376130666464386533366231323362653061643462663266
34396432633530356137653761613739613161623864356439306562646231363432663832653938
38373734623566636531376530383232336138363836663733616665313335636463393564373662
31396437633339356536336464313335346632326361663566363464313266653538326330386565
39303963353066303031363631333864636638666231656131653232356330323530326239346564
39343836373538656231373531636163663932653763626431623964383735343332393932376262
33323762663165306536383561396364363934326265636363376536323032373966303434656432
32303532363063613965633937353964366130333638663934653064343036316462316436373334
65353630366637346333633465636630383763383161626563323464613061383966396633393533
38643866323764396237643663666439626435343530646636373937383163336232666166323936
31363563346263353537323237636237646136346333333061383236373762653466336161336230
61393765303065356533643237636230396332333638353539356439653732393365353762666332
36393336366334336535343263613863316531653033393831346631343437356631393034383832
66353766393032396237333662393438363236386365643639623230623364626164653039363632
33353062376465633237326436636463306531343538336136376334643837626538653064653064
62333565616136396536316438303533363134303261303331376633646334323333643431376239
39373339623461616239626665333564376161613663646562623937653665383132393837656231
35626638656564346339653738313230303865343334346630323163343232323234346165373761
346166313036396337393636393238363339
