---
top_level_domain: dev-analytics.isis.cclrc.ac.uk

minio_api_port: 9000
minio_console_port: 9001
minio_console_base_path: /minio-ui

s3_endpoint: "https://{{ top_level_domain }}:{{ minio_api_port }}"
s3_region: minio # not used but can be required by apis
s3_access_key_id: "{{ vault_minio_root_user }}"
s3_access_secret: "{{ vault_minio_root_passwd }}"

lakekeeper_bucket_prefix: warehouse-

elt_cron_jobs_state: absent
