---
- name: Provision VM for keycloak
  import_playbook: impl/provision_openstack_vm.yml
  vars:
    config_files:
      - "configs/{{ vm_env }}/vault.yml"
      - "configs/{{ vm_env }}/keycloak.yml"
