name: Static checks

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  staticcheck:
    name: static checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - name: "Install prek"
        run: >
          python -m pip install prek
      - name: "Run prek"
        run: >
          prek --all-files --verbose
