name: Publish a Docker image for our Superset build

on:
  push:
    branches:
      - "main"
    paths:
      - "infra/container-images/analytics-data-platform-superset/Dockerfile"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "infra/container-images/analytics-data-platform-superset/Dockerfile"
      - ".github/workflows/docker-superset.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  ORG_NAME: isisneutronmuon
  IMAGE_NAME: analytics-data-platform-superset
  PUBLISH: false

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Compute fully qualified image name
        run: echo "FQ_IMAGE_NAME=${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: infra/container-images/${{ env.IMAGE_NAME }}
          push: ${{ env.PUBLISH }}
          tags: |
            ${{ env.FQ_IMAGE_NAME }}:${{ github.sha }}
            ${{ env.FQ_IMAGE_NAME }}:latest

      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built.
      # See [Using artifact attestations to establish provenance for builds](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds)
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.FQ_IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: ${{ env.PUBLISH }}
