name: Unit tests for elt-common package
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/elt-common_unit_tests.yml"
      - "elt-common/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/elt-common_unit_tests.yml"
      - "elt-common/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: elt-common unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run unit tests
        uses: ./.github/actions/run-pytest-with-uv
        with:
          pyproject-directory: elt-common
          pytest-file-or-dir: tests/unit_tests
          uv-cache-dependency-glob: elt-common/pyproject.toml
