name: End-to-end tests for elt-common package
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/elt-common_e2e_tests.yml"
      - "ansible-docker/roles/lakekeeper/files/bootstrap-warehouse.py"
      - "infra/local/**"
      - "elt-common/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/elt-common_e2e_tests.yml"
      - "ansible-docker/roles/lakekeeper/files/bootstrap-warehouse.py"
      - "infra/local/**"
      - "elt-common/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

env:
  TRINO_CATALOG_STORE: memory

jobs:
  test:
    name: elt-common end-to-end tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add adp-router to /etc/hosts
        shell: bash -l {0}
        run: |
          echo "127.0.0.1    adp-router" | sudo tee -a /etc/hosts

      - name: Run end-to-end tests
        uses: ./.github/actions/run-pytest-with-uv
        with:
          compose-file-path: infra/local/docker-compose.yml
          pyproject-directory: elt-common
          pytest-file-or-dir: tests/e2e_tests
          uv-cache-dependency-glob: elt-common/pyproject.toml

      - name: Remove adp-router from /etc/hosts
        shell: bash -l {0}
        run: |
          sudo sed -i -e '/adp-router/d' /etc/hosts
