name: End-to-end tests for extract and load scripts in the warehouse
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/warehouses_e2e_tests.yml"
      - "elt-common/**"
      - "warehouses/accelerator/extract_load/opralogweb/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/warehouses_e2e_tests.yml"
      - "elt-common/**"
      - "warehouses/accelerator/extract_load/opralogweb/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: warehouses end-to-end tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Add adp-router to /etc/hosts
        shell: bash -l {0}
        run: |
          echo "127.0.0.1    adp-router" | sudo tee -a /etc/hosts

      - name: Run end-to-end tests
        uses: ./.github/actions/run-pytest-with-uv
        with:
          compose-file-path: infra/local/docker-compose.yml
          install-cmd: uv sync --locked --dev --script extract_and_load.py
          pytest-file-or-dir: tests
          uv-cache-dependency-glob: elt-common/pyproject.toml
          working-directory: warehouses/accelerator/extract_load/opralogweb

      - name: Remove adp-router from /etc/hosts
        shell: bash -l {0}
        run: |
          sudo sed -i -e '/adp-router/d' /etc/hosts
